"use client";
import { useSearchParams } from "next/navigation";
import { useEffect, useState } from "react";

export default function ChatInner() {
  const searchParams = useSearchParams();
  const type = searchParams.get("type");
  const [doc, setDoc] = useState("");
  const [loading, setLoading] = useState(false);

  function cleanText(text: string) {
    return text
      .replace(/[#*`]/g, "")
      .replace(/\n{2,}/g, "\n\n")
      .trim();
  }

  useEffect(() => {
    if (!type) return;

    async function generate() {
      setLoading(true);
      try {
        const businessName = localStorage.getItem("businessName") || "";
        const industry = localStorage.getItem("industry") || "";
        const employees = localStorage.getItem("employees") || "";
        const complianceScore = localStorage.getItem("complianceScore") || "";
        const gdprIssues = JSON.parse(localStorage.getItem("gdprIssues") || "[]");
        const authIssues = JSON.parse(localStorage.getItem("authIssues") || "[]");
        const securityIssues = JSON.parse(localStorage.getItem("securityIssues") || "[]");

        const res = await fetch("/api/generate", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            type,
            businessName,
            industry,
            employees,
            complianceScore,
            gdprIssues,
            authIssues,
            securityIssues,
          }),
        });

        const data = await res.json();
        const cleaned = cleanText(data.document);
        setDoc(cleaned);

        const savedDocs = JSON.parse(localStorage.getItem("generatedDocs") || "{}");
        savedDocs[type] = cleaned;
        localStorage.setItem("generatedDocs", JSON.stringify(savedDocs));
      } catch (err) {
        console.error(err);
      }
      setLoading(false);
    }

    generate();
  }, [type]);

  const paragraphs = doc.split("\n\n");

  return (
    <div className="min-h-screen bg-white text-black p-12">
      <h1 className="text-3xl font-semibold mb-10">{type} Report</h1>
      {loading && <p>Generating document...</p>}
      {!loading && doc && (
        <div className="max-w-3xl bg-white border border-neutral-200 rounded-xl p-10">
          <div className="text-sm text-neutral-500 mb-8">
            Generated by <strong>ComplyPilot</strong> • {new Date().toLocaleDateString()}
          </div>
          <div className="space-y-5 leading-relaxed text-neutral-800">
            {paragraphs.map((p, i) => (
              <p key={i}>{p}</p>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}
